name: Daily Workout Processing

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily
  workflow_dispatch: # Allows manual trigger

jobs:
  process-workouts:
    runs-on: ubuntu-latest

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # Add other environment variables as needed

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run workout processor
        run: node dist/index.js
